-- Table: public.customer

-- DROP TABLE public.customer;

CREATE TABLE public.customer
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    last_name text COLLATE pg_catalog."default" NOT NULL,
    district text COLLATE pg_catalog."default" NOT NULL,
    sale double precision NOT NULL,
    CONSTRAINT customer_pkey PRIMARY KEY (id)
)
WITH (
         OIDS = FALSE
     )
    TABLESPACE pg_default;

ALTER TABLE public.customer
    OWNER to postgres;

-- Table: public.book

-- DROP TABLE public.book;

CREATE TABLE public.book
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    storage text COLLATE pg_catalog."default" NOT NULL,
    count integer NOT NULL,
    CONSTRAINT book_pkey PRIMARY KEY (id)
)
WITH (
         OIDS = FALSE
     )
    TABLESPACE pg_default;

ALTER TABLE public.book
    OWNER to postgres;
-- Table: public.purchase

-- DROP TABLE public.purchase;


-- Table: public.shop

-- DROP TABLE public.shop;

CREATE TABLE public.shop
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    name text COLLATE pg_catalog."default" NOT NULL,
    district text COLLATE pg_catalog."default" NOT NULL,
    commission double precision NOT NULL,
    CONSTRAINT shop_pkey PRIMARY KEY (id)
)
WITH (
         OIDS = FALSE
     )
    TABLESPACE pg_default;

ALTER TABLE public.shop
    OWNER to postgres;


CREATE TABLE public.purchase
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    date date NOT NULL,
    seller integer NOT NULL,
    customer integer NOT NULL,
    book integer NOT NULL,
    count integer NOT NULL,
    price integer NOT NULL,
    CONSTRAINT purchase_pkey PRIMARY KEY (id),
    CONSTRAINT book_key FOREIGN KEY (book)
        REFERENCES public.book (id) MATCH SIMPLE
        ON UPDATE NO ACTION
           ON DELETE NO ACTION,
                  CONSTRAINT customer_key FOREIGN KEY (customer)
              REFERENCES public.customer (id) MATCH SIMPLE
              ON UPDATE NO ACTION
                 ON DELETE NO ACTION,
                        CONSTRAINT seller_key FOREIGN KEY (seller)
                    REFERENCES public.shop (id) MATCH SIMPLE
                    ON UPDATE NO ACTION
                       ON DELETE NO ACTION
                          )
WITH (
         OIDS = FALSE
     )
    TABLESPACE pg_default;

ALTER TABLE public.purchase
    OWNER to postgres;

INSERT INTO public.book (name, price, storage, count) VALUES('Clockwork Orange',180,'Sormovskiy',10);
INSERT INTO public.book (name, price, storage, count) VALUES('Art of programming',3100,'Sormovskiy',25);
INSERT INTO public.book (name, price, storage, count) VALUES('War and Peace',31450,'Nizhegorodskiy',31);
INSERT INTO public.book (name, price, storage, count) VALUES('100 years of loneliness',1450,'Nizhegorodskiy',33);
INSERT INTO public.book (name, price, storage, count) VALUES('Crime and Punishment',950,'Avtozavodskiy',45);
INSERT INTO public.book (name, price, storage, count) VALUES('Norwegian Forest',640,'Avtozavodskiy',24);
INSERT INTO public.book (name, price, storage, count) VALUES('Dandelion Wine',430,'Sovetskiy',15);
INSERT INTO public.book (name, price, storage, count) VALUES('Introduction to Psychoanalysis',300,'Sovetskiy',17);
INSERT INTO public.book (name, price, storage, count) VALUES('Harry potter and the philosopher stone',1000,'Sovetskiy',8);
INSERT INTO public.book (name, price, storage, count) VALUES('Windows for students',1000,'Avtozavodskiy',8);

INSERT INTO public.customer (last_name, district, sale) VALUES('Ivanov','Sovetskiy','0.2');
INSERT INTO public.customer (last_name, district, sale) VALUES('Volkov','Sovetskiy','0.65');
INSERT INTO public.customer (last_name, district, sale) VALUES('Sidorova','Sovetskiy','0.53');
INSERT INTO public.customer (last_name, district, sale) VALUES('Petrov','Avtozavodskiy','0.54');
INSERT INTO public.customer (last_name, district, sale) VALUES('Petrova','Avtozavodskiy','0.3');
INSERT INTO public.customer (last_name, district, sale) VALUES('Beglov','Avtozavodskiy','0.7');
INSERT INTO public.customer (last_name, district, sale) VALUES('Krupnov','Sormovskiy','0.2');
INSERT INTO public.customer (last_name, district, sale) VALUES('Sizov','Sormovskiy','0.2');
INSERT INTO public.customer (last_name, district, sale) VALUES('Sergeeva','Sormovskiy','0.4');
INSERT INTO public.customer (last_name, district, sale) VALUES('Mironova','Nizhegorodskiy','0.14');
INSERT INTO public.customer (last_name, district, sale) VALUES('Volkova','Sovetskiy','0.13');


INSERT INTO public.shop (name, district, commission) VALUES ('Chitay-gorod','Sovetskiy','0.3');
INSERT INTO public.shop (name, district, commission) VALUES ('Dirizhabl','Avtozavodskiy','0.1');
INSERT INTO public.shop (name, district, commission) VALUES ('Book House','Sormovskiy','0.3');
INSERT INTO public.shop (name, district, commission) VALUES ('Book Shop','Nizhegorodskiy','0.2');

INSERT INTO public.purchase (date, seller, customer, book, count, price) VALUES ('2019-05-27',2,4,1,3,2344);
INSERT INTO public.purchase (date, seller, customer, book, count, price) VALUES ('2018-04-23',3,9,1,1,445);
INSERT INTO public.purchase (date, seller, customer, book, count, price) VALUES ('2019-01-27',4,3,1,2,332);
INSERT INTO public.purchase (date, seller, customer, book, count, price) VALUES ('2019-02-27',1,1,3,4,6032);
INSERT INTO public.purchase (date, seller, customer, book, count, price) VALUES ('2019-03-27',2,4,5,2,3424);
INSERT INTO public.purchase (date, seller, customer, book, count, price) VALUES ('2019-09-09',4,11,8,1,43553);
INSERT INTO public.purchase (date, seller, customer, book, count, price) VALUES ('2019-05-27',1,2,3,2,67000);
INSERT INTO public.purchase (date, seller, customer, book, count, price) VALUES ('2019-07-14',3,7,2,1,4200);
